openapi: 3.0.0
info:
  title: GitHub Issue Summary API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /summary/{orgName}/repository/{repoName}:
    get:
      summary: Retrieve GitHub issue summary
      description: Returns a list of GitHub issues for a given organization and repository.
      parameters:
        - name: orgName
          in: path
          required: true
          description: The name of the organization.
          schema:
            type: string
        - name: repoName
          in: path
          required: true
          description: The name of the repository.
          schema:
            type: string
      responses:
        '200':
          description: A list of GitHub issues
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Issue'
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    Issue:
      type: object
      properties:
        number:
          type: integer
          description: The unique identifier for the issue.
        title:
          type: string
          description: The title of the issue.
